# Data Source Settings
spring:
  datasource:
    url: jdbc:postgresql://localhost/boot_spa
    username: postgres
    password: P0stgres

# Security Settings
security:
  oauth2:
    client:
      clientId: arip
      clientSecret: aripsecret
      authorized-grant-types: password, authorization_code, refresh_token
      scope: read, write
      accessTokenValiditySeconds: 3600