security:
  oauth2:
    client:
      clientId: arip
      clientSecret: aripsecret
      authorized-grant-types: password, authorization_code, refresh_token
      scope: read, write
      accessTokenValiditySeconds: 3600
    resource:
      filter-order: 3