spring:
  main:
    banner-mode: "off"

  # Data Source Settings
  datasource:
    url: jdbc:postgresql://localhost/boot_spa
    username: postgres
    password: P0stgres

  data:
    rest:
      basePath: /api