spring:
  main:
    banner-mode: "off"

  # Data Source Settings
  datasource:
    url: jdbc:postgresql://localhost/boot_spa
    username: postgres
    password: P0stgres

  data:
    rest:
      basePath: /api

# Security Settings
security:
  oauth2:
    client:
      clientId: arip
      clientSecret: aripsecret
      authorizedGrantTypes: password, authorization_code, refresh_token
      scope: read, write
      accessTokenValiditySeconds: 3600